import type React from 'react';

export const EMOJI_OPTIONS = ['🚀', '🎯', '⚡', '🔥', '💡', '🛠️', '📦', '🎨', '🌱', '🔮', '📊', '🏆'];

export const S = {
  page: {
    minHeight: '100vh',
    background: '#F5F3EF',
    fontFamily: "'DM Sans', -apple-system, BlinkMacSystemFont, sans-serif",
  } as React.CSSProperties,
  nav: {
    background: '#1A1A1A',
    padding: '11px 32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  } as React.CSSProperties,
  logo: { fontSize: 18, fontWeight: 700, color: '#FFF', letterSpacing: '-0.03em' } as React.CSSProperties,
  accent: { color: '#FF6B35' } as React.CSSProperties,
  container: { maxWidth: 680, margin: '0 auto', padding: '40px 24px' } as React.CSSProperties,
  card: {
    background: '#FFF',
    borderRadius: 16,
    border: '1px solid #E8E6E1',
    padding: '40px 48px',
    boxShadow: '0 4px 24px rgba(0,0,0,0.04)',
  } as React.CSSProperties,
  label: {
    display: 'block',
    fontSize: 13,
    fontWeight: 600,
    color: '#1A1A1A',
    marginBottom: 6,
  } as React.CSSProperties,
  input: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: 8,
    border: '1px solid #E8E6E1',
    fontSize: 14,
    color: '#1A1A1A',
    background: '#FAFAFA',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    outline: 'none',
  } as React.CSSProperties,
  textarea: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: 8,
    border: '1px solid #E8E6E1',
    fontSize: 14,
    color: '#1A1A1A',
    background: '#FAFAFA',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    outline: 'none',
    resize: 'vertical',
    minHeight: 100,
  } as React.CSSProperties,
  btnPrimary: {
    padding: '10px 24px',
    borderRadius: 8,
    border: 'none',
    background: '#1A1A1A',
    color: '#FFF',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
  } as React.CSSProperties,
  btnSecondary: {
    padding: '10px 24px',
    borderRadius: 8,
    border: '1px solid #E8E6E1',
    background: '#FFF',
    color: '#6B6560',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
  } as React.CSSProperties,
  field: { marginBottom: 20 } as React.CSSProperties,
};
