import { Project } from '../types';

export const PROJECTS: Project[] = [
  {
    id: '1',
    name: 'Checkout Revamp',
    emoji: '💳',
    health: 'on-track',
    healthLabel: 'On Track',
    pmLead: 'Julie P.',
    techLead: 'Marie D.',
    team: 'Payments',
    period: 'Week 7 · Feb 17–23',
    progress: 68,
    prevProgress: 61,
    targetDate: 'Mar 15',
    daysToTarget: 20,
    sources: { slack: 47, linear: 23, notion: 4 },
    objective: {
      goal: 'Reduce cart abandonment rate from 18% to 12%',
      origin: 'Q1 Roadmap · Product Board Review, Jan 6',
      keyResults: [
        { text: 'Stripe Connect integrated', done: true },
        { text: 'Checkout flow < 3 steps', done: false },
        { text: 'Mobile conversion +15%', done: false },
      ],
    },
    narrative:
      'Strong engineering velocity — 5 tickets merged, 2 in review. The Stripe Connect decision was finalized after a 3-day discussion, closing a key architectural question. The main risk is design-side: the confirmation screen handoff from Sarah is 3 days late, which could push the launch by a week. Product-wise, the current implementation aligns with the original spec, but the team is considering dropping the guest checkout shortcut to hit the deadline — this would impact the abandonment KR.',
    decisions: [
      {
        text: 'Stripe Connect over custom payment integration',
        tradeoff: 'Faster to ship (+2 weeks saved), but less customizable for future multi-currency support',
        who: 'Marie D. + Julie P.',
        where: 'Slack #checkout-v2',
        when: 'Wed, Feb 19',
        alignedWithIntent: true,
      },
      {
        text: 'Postponing Apple Pay to v2.1',
        tradeoff: 'Reduces scope, but Apple Pay users have 22% higher conversion — could limit KR impact',
        who: 'Julie P.',
        where: 'Linear CHK-89',
        when: 'Thu, Feb 20',
        alignedWithIntent: 'partial',
      },
    ],
    drift: {
      level: 'low',
      label: 'Minor Drift',
      details:
        'Guest checkout shortcut may be cut for deadline. Original spec identified this as a key driver of the abandonment KR (est. 3-4% impact). Recommend: explicit decision with CPO before cutting.',
    },
    blockers: [
      {
        text: 'Figma handoff for confirmation screen not delivered',
        owner: 'Sarah K.',
        severity: 'medium',
        since: '3 days',
        impact: 'Could delay launch by ~1 week',
      },
    ],
    delivery: {
      merged: 5,
      inReview: 2,
      blocked: 1,
      created: 3,
      velocity: '+18%',
      velocityLabel: 'vs last week',
    },
    threads: [
      {
        title: 'Stripe Connect vs Custom integration',
        participants: ['Marie D.', 'Thomas R.', 'Julie P.'],
        messages: 14,
        outcome: 'Decision: Stripe Connect',
        channel: '#checkout-v2',
      },
      {
        title: 'Should we cut guest checkout for deadline?',
        participants: ['Julie P.', 'Marie D.'],
        messages: 6,
        outcome: 'Open — needs CPO input',
        channel: '#checkout-v2',
      },
    ],
  },
  {
    id: '2',
    name: 'Search Rewrite',
    emoji: '🔍',
    health: 'at-risk',
    healthLabel: 'At Risk',
    pmLead: 'Alex M.',
    techLead: 'Thomas R.',
    team: 'Core Platform',
    period: 'Week 4 · Feb 17–23',
    progress: 34,
    prevProgress: 31,
    targetDate: 'Apr 10',
    daysToTarget: 46,
    sources: { slack: 82, linear: 15, notion: 2 },
    objective: {
      goal: 'Improve search relevance score from 64% to 85% and reduce p95 latency to <200ms',
      origin: 'Q1 Roadmap · Tech Debt Review, Dec 12',
      keyResults: [
        { text: 'OpenSearch migration complete', done: false },
        { text: 'Relevance score > 85%', done: false },
        { text: 'p95 latency < 200ms', done: false },
      ],
    },
    narrative:
      "Project is falling behind — only 2 tickets completed vs 6 planned. A critical data consistency issue discovered Monday consumed most of the team's bandwidth. The OpenSearch migration is proving significantly more complex than estimated. An architecture decision on index sharding is blocking further progress and requires CTO review. At current velocity, the April 10 target is at serious risk — the team estimates a 2-3 week delay unless the sharding decision is made this week.",
    decisions: [
      {
        text: 'Switching from managed Elasticsearch to OpenSearch',
        tradeoff: 'Better cost structure and AWS-native, but migration path is more complex than initially estimated',
        who: 'Thomas R.',
        where: 'Slack #search-rewrite',
        when: 'Mon, Feb 17',
        alignedWithIntent: true,
      },
    ],
    drift: {
      level: 'high',
      label: 'Significant Drift',
      details:
        'Original scope was "re-index and optimize ranking." Current work has expanded into a full infrastructure migration (Elasticsearch → OpenSearch). Scope increased ~40% without formal Product review. The relevance improvements haven\'t started yet — all effort is on migration.',
    },
    blockers: [
      {
        text: 'Data consistency gap between legacy and new search indices',
        owner: 'Thomas R.',
        severity: 'high',
        since: '5 days',
        impact: 'All ranking work blocked until resolved',
      },
      {
        text: 'Architecture decision on index sharding strategy',
        owner: 'Victor L. (CTO)',
        severity: 'high',
        since: '3 days',
        impact: 'Team idle on core path without this decision',
      },
    ],
    delivery: {
      merged: 2,
      inReview: 1,
      blocked: 3,
      created: 2,
      velocity: '-62%',
      velocityLabel: 'vs last week',
    },
    threads: [
      {
        title: 'Data sync issue — legacy index 6h behind',
        participants: ['Thomas R.', 'Marie D.'],
        messages: 23,
        outcome: 'Investigation ongoing',
        channel: '#search-rewrite',
      },
      {
        title: 'Do we need to rethink sharding entirely?',
        participants: ['Thomas R.', 'Victor L.'],
        messages: 8,
        outcome: 'Waiting for CTO decision',
        channel: '#search-rewrite',
      },
    ],
  },
  {
    id: '3',
    name: 'Onboarding V2',
    emoji: '🚀',
    health: 'on-track',
    healthLabel: 'On Track',
    pmLead: 'Julie P.',
    techLead: 'Léa B.',
    team: 'Growth',
    period: 'Week 2 · Feb 17–23',
    progress: 22,
    prevProgress: 11,
    targetDate: 'May 2',
    daysToTarget: 68,
    sources: { slack: 29, linear: 18, notion: 7 },
    objective: {
      goal: 'Increase Day-7 activation rate from 34% to 55%',
      origin: 'Q1 Roadmap · Growth Review, Jan 13',
      keyResults: [
        { text: 'User research synthesis done', done: true },
        { text: 'Progressive profiling shipped', done: false },
        { text: 'A/B test 3-step vs 5-step launched', done: false },
      ],
    },
    narrative:
      'Ahead of schedule. User research synthesis was completed and specs are finalized in Notion. Julie and Léa aligned on the progressive profiling approach, which directly supports the activation KR. 4 new tickets created and estimated. The project is well-scoped and the team has strong Product-Eng alignment on the approach.',
    decisions: [
      {
        text: 'Progressive profiling instead of single long form',
        tradeoff: 'Better UX and higher expected completion, but adds 1 week of engineering complexity',
        who: 'Julie P. + Léa B.',
        where: 'Notion Onboarding V2 Spec',
        when: 'Tue, Feb 18',
        alignedWithIntent: true,
      },
      {
        text: 'A/B test between 3-step and 5-step onboarding flows',
        tradeoff: 'Adds 3-4 days to validate, but de-risks the final approach with data',
        who: 'Julie P.',
        where: 'Slack #growth-eng',
        when: 'Thu, Feb 20',
        alignedWithIntent: true,
      },
    ],
    drift: {
      level: 'none',
      label: 'Aligned',
      details: 'Implementation matches original spec and product intent. No divergence detected.',
    },
    blockers: [],
    delivery: {
      merged: 1,
      inReview: 0,
      blocked: 0,
      created: 4,
      velocity: '+100%',
      velocityLabel: 'from zero (project start)',
    },
    threads: [
      {
        title: 'Research synthesis — 3 key patterns',
        participants: ['Julie P.', 'Léa B.', 'Alex M.'],
        messages: 11,
        outcome: 'Patterns validated, specs updated',
        channel: '#growth-eng',
      },
    ],
  },
];
